// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	DeleteCustomer(ctx context.Context, id int64) error
	GetCustomer(ctx context.Context, id int64) (Customer, error)
	GetCustomerForUpdate(ctx context.Context, id int64) (Customer, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	UpdateCustomerAddress(ctx context.Context, arg UpdateCustomerAddressParams) (Customer, error)
}

var _ Querier = (*Queries)(nil)
